In [14]:
!git init

!git remote add origin https://github.com/GuptaShivani4908/data-science.git

!git config --global user.name "GuptaShivani4908"

!git config --global user.email "shivanigupta4908@gmail.com"

!git branch -M main

!git add .

!git commit -m "pandas code"

!git push -u origin main --force

Reinitialized existing Git repository in C:/Users/shiva/data science/.git/

error: remote origin already exists.

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean
branch 'main' set up to track 'origin/main'.

Everything up-to-date

In [10]:
!git add .
!git commit -m "Added new notebook"
!git push

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

Everything up-to-date

In [14]:
!git remote set-url origin https://github.com/GuptaShivani4908/data-science.git

In [7]:
!git remote set-url origin https://github.com/GuptaShivani4908/data-science.git

In [10]:
!git remote set-url origin https://github.com/GuptaShivani4908/data-science.git

In [7]:

import pandas as pd

In [12]:
!git remote -v

origin	https://github.com/GuptaShivani4908/data-science.git (fetch)
origin	https://github.com/GuptaShivani4908/data-science.git (push)

In [35]:
import pandas as pd

In [56]:
!git config --global user.name "GuptaShivani4908"
!git config --global user.email "shivanigupta4908@gmail.com"

'git' is not recognized as an internal or external command,
operable program or batch file.
'git' is not recognized as an internal or external command,
operable program or batch file.

In [36]:
s = pd.Series([77,27,80,66,73,33])

In [37]:
s

0    77
1    27
2    80
3    66
4    73
5    33
dtype: int64

In [38]:
pd.DataFrame(s, columns =["Name","Marks"])

ValueError: Shape of passed values is (6, 1), indices imply (6, 2)

In [ ]:
type(s)

In [39]:
s = pd.Series([77,27,80,66,73,33] , index = ["shivani","pankaj","honey","kalu","bhalu","pinky"])

In [11]:
s
s
s
s
s
s
s
s
s

NameError: name 's' is not defined

In [41]:
s["shivani"]

np.int64(77)

In [42]:
data ={"name":["shiv", "kalu", "bhalu"],
      "age": [ 23,25,22],
      "city": [ "london", "canada", "california"]
}

In [43]:
 df = pd.DataFrame(data)

In [44]:
df

    name  age        city
0   shiv   23      london
1   kalu   25      canada
2  bhalu   22  california

In [45]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [46]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [47]:
data = [["shiv", 34], [ "kaluua ",20]]

In [48]:
data

[['shiv', 34], ['kaluua ', 20]]

In [49]:
pd.DataFrame(data, columns =["Name","Marks"])

      Name  Marks
0     shiv     34
1  kaluua      20

In [50]:
data = {"a": [ 4,5,3] , "b": [55,65,34]}

In [51]:
data

{'a': [4, 5, 3], 'b': [55, 65, 34]}

In [52]:
df = pd.DataFrame(data)

In [53]:
df

   a   b
0  4  55
1  5  65
2  3  34

In [54]:
 import numpy as np

In [55]:
arr = np.array([[1,2,],[5,6]])

In [56]:
df = pd.DataFrame(arr, columns =["A","B"] )

In [57]:
df

   A  B
0  1  2
1  5  6

In [63]:
import pandas as pd
df =pd.read_excel("studentdata.xlsx")

In [60]:
pip install openpyxl

Collecting openpyxl
  Downloading openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Downloading et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Downloading openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Downloading et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl

   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   -------------------- ------------------- 1/2 [openpyxl]
   ---------------------------------------- 2/2 [openpyxl]

Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [61]:
!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\shiva\appdata\local\programs\python\python310\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\shiva\appdata\local\programs\python\python310\lib\site-packages (from openpyxl) (2.0.0)

[notice] A new release of pip is available: 25.2 -> 26.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
df

               Name Student                  School  Marks
0     Emily Johnson  STU001       Riverside Academy     85
1      Michael Chen  STU002            Oakwood High     92
2      Sarah Miller  STU003          Pinecrest Prep     78
3      David Wilson  STU004       Maple Leaf School     88
4    Jessica Garcia  STU005   Cedar Grove Institute     95
5      James Taylor  STU006  Willow Creek Secondary     72
6   Ashley Anderson  STU007       Birchwood Academy     84
7   Christopher Lee  STU008        Silver Lake High     91
8   Amanda Martinez  STU009   Redwood International     80
9  Matthew Robinson  STU010    Juniper Hills School     87

In [69]:
df = pd.read_csv("studentdata - Sheet1.csv")

In [70]:
df

               Name Student                  School  Marks
0     Emily Johnson  STU001       Riverside Academy     85
1      Michael Chen  STU002            Oakwood High     92
2      Sarah Miller  STU003          Pinecrest Prep     78
3      David Wilson  STU004       Maple Leaf School     88
4    Jessica Garcia  STU005   Cedar Grove Institute     95
5      James Taylor  STU006  Willow Creek Secondary     72
6   Ashley Anderson  STU007       Birchwood Academy     84
7   Christopher Lee  STU008        Silver Lake High     91
8   Amanda Martinez  STU009   Redwood International     80
9  Matthew Robinson  STU010    Juniper Hills School     87

In [71]:
df = pd.read_json("data.json")

ValueError: If using all scalar values, you must pass an index

In [72]:
df

               Name Student                  School  Marks
0     Emily Johnson  STU001       Riverside Academy     85
1      Michael Chen  STU002            Oakwood High     92
2      Sarah Miller  STU003          Pinecrest Prep     78
3      David Wilson  STU004       Maple Leaf School     88
4    Jessica Garcia  STU005   Cedar Grove Institute     95
5      James Taylor  STU006  Willow Creek Secondary     72
6   Ashley Anderson  STU007       Birchwood Academy     84
7   Christopher Lee  STU008        Silver Lake High     91
8   Amanda Martinez  STU009   Redwood International     80
9  Matthew Robinson  STU010    Juniper Hills School     87

In [73]:
df.head()

             Name Student                 School  Marks
0   Emily Johnson  STU001      Riverside Academy     85
1    Michael Chen  STU002           Oakwood High     92
2    Sarah Miller  STU003         Pinecrest Prep     78
3    David Wilson  STU004      Maple Leaf School     88
4  Jessica Garcia  STU005  Cedar Grove Institute     95

In [74]:
df.tail()

               Name Student                  School  Marks
5      James Taylor  STU006  Willow Creek Secondary     72
6   Ashley Anderson  STU007       Birchwood Academy     84
7   Christopher Lee  STU008        Silver Lake High     91
8   Amanda Martinez  STU009   Redwood International     80
9  Matthew Robinson  STU010    Juniper Hills School     87

In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Name     10 non-null     object
 1   Student  10 non-null     object
 2   School   10 non-null     object
 3   Marks    10 non-null     int64
dtypes: int64(1), object(3)
memory usage: 448.0+ bytes

In [76]:
df.describe()

          Marks
count  10.00000
mean   85.20000
std     7.00476
min    72.00000
25%    81.00000
50%    86.00000
75%    90.25000
max    95.00000

In [78]:
df.columns

Index(['Name', 'Student', 'School', 'Marks'], dtype='object')

In [79]:
df.shape

(10, 4)

In [84]:
df = pd.read_csv("actor - Sheet1.csv")

In [85]:
df

,Actor,Film,Year,Genre,Box Office,IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
1,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
2,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
3,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
5,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3
7,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
8,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
9,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
11,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
12,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
15,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
16,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
17,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
18,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
19,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
21,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
22,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
25,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
27,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
28,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
29,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3

In [86]:
df['Actor']

0      Leonardo DiCaprio
1           Meryl Streep
2      Robert Downey Jr.
3     Scarlett Johansson
4              Brad Pitt
5         Angelina Jolie
6             Tom Cruise
7        Natalie Portman
8             Will Smith
9          Julia Roberts
10        Morgan Freeman
11     Jennifer Lawrence
12     Denzel Washington
13       Charlize Theron
14           Johnny Depp
15        Sandra Bullock
16            Matt Damon
17            Emma Stone
18          Ryan Gosling
19         Anne Hathaway
20        Christian Bale
21          Kate Winslet
22          Hugh Jackman
23           Viola Davis
24       Joaquin Phoenix
25           Emily Blunt
26     Samuel L. Jackson
27             Amy Adams
28             Tom Hanks
29        Cate Blanchett
Name: Actor, dtype: object

In [87]:
df['Actor'][3]

'Scarlett Johansson'

In [88]:
type(df['Actor'])

pandas.core.series.Series

In [89]:
df[['Actor', 'IMDb']]

                 Actor  IMDb
0    Leonardo DiCaprio   8.8
1         Meryl Streep   6.9
2    Robert Downey Jr.   7.9
3   Scarlett Johansson   6.4
4            Brad Pitt   8.8
5       Angelina Jolie   6.9
6           Tom Cruise   8.3
7      Natalie Portman   8.0
8           Will Smith   7.3
9        Julia Roberts   7.1
10      Morgan Freeman   9.3
11   Jennifer Lawrence   7.2
12   Denzel Washington   7.7
13     Charlize Theron   8.1
14         Johnny Depp   8.1
15      Sandra Bullock   7.7
16          Matt Damon   8.0
17          Emma Stone   8.0
18        Ryan Gosling   7.8
19       Anne Hathaway   7.5
20      Christian Bale   9.0
21        Kate Winslet   7.9
22        Hugh Jackman   7.5
23         Viola Davis   7.2
24     Joaquin Phoenix   8.4
25         Emily Blunt   7.5
26   Samuel L. Jackson   8.9
27           Amy Adams   7.9
28           Tom Hanks   7.8
29      Cate Blanchett   7.3

In [90]:
df.loc[1] #by label

Actor                  Meryl Streep
Film          The Devil Wears Prada
Year                           2006
Genre                  Comedy/Drama
Box Office                  $326.7M
IMDb                            6.9
Name: 1, dtype: object

In [91]:
df.iloc[1]# number by position

Actor                  Meryl Streep
Film          The Devil Wears Prada
Year                           2006
Genre                  Comedy/Drama
Box Office                  $326.7M
IMDb                            6.9
Name: 1, dtype: object

In [94]:
df.loc[7,'IMDb'] #start wirh 1

np.float64(8.0)

In [95]:
df.iloc[7,5] # start with o

np.float64(8.0)

In [97]:
df.loc[0:2, ["Actor","IMDb", "Film"]]

               Actor  IMDb                   Film
0  Leonardo DiCaprio   8.8              Inception
1       Meryl Streep   6.9  The Devil Wears Prada
2  Robert Downey Jr.   7.9               Iron Man

In [99]:
df.iloc[0:2, 0:2]

               Actor                   Film
0  Leonardo DiCaprio              Inception
1       Meryl Streep  The Devil Wears Prada

In [100]:
df.at[0,"Actor"]

'Leonardo DiCaprio'

In [101]:
df.iat[0,0]

'Leonardo DiCaprio'

In [107]:
df[df['IMDb']>8]['Actor'] #filter chaining

0     Leonardo DiCaprio
4             Brad Pitt
6            Tom Cruise
10       Morgan Freeman
13      Charlize Theron
14          Johnny Depp
20       Christian Bale
24      Joaquin Phoenix
26    Samuel L. Jackson
Name: Actor, dtype: object

In [108]:
df[df['IMDb']>8]

,Actor,Film,Year,Genre,Box Office,IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9

In [110]:
df[(df['IMDb']>8) &(df['Year']>2018)] #and

              Actor               Film  Year   Genre Box Office  IMDb
6        Tom Cruise  Top Gun: Maverick  2022  Action    $1.496B   8.3
24  Joaquin Phoenix              Joker  2019   Crime    $1.074B   8.4

In [113]:
df[(df['IMDb']>8) | (df['Year']>2018)] #or

,Actor,Film,Year,Genre,Box Office,IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9

In [116]:
df.query("Year>2019 and IMDb > 7")

        Actor               Film  Year   Genre Box Office  IMDb
6  Tom Cruise  Top Gun: Maverick  2022  Action    $1.496B   8.3

In [117]:
df2 = df[["Actor" ,'IMDb']]

In [118]:
df2

                 Actor  IMDb
0    Leonardo DiCaprio   8.8
1         Meryl Streep   6.9
2    Robert Downey Jr.   7.9
3   Scarlett Johansson   6.4
4            Brad Pitt   8.8
5       Angelina Jolie   6.9
6           Tom Cruise   8.3
7      Natalie Portman   8.0
8           Will Smith   7.3
9        Julia Roberts   7.1
10      Morgan Freeman   9.3
11   Jennifer Lawrence   7.2
12   Denzel Washington   7.7
13     Charlize Theron   8.1
14         Johnny Depp   8.1
15      Sandra Bullock   7.7
16          Matt Damon   8.0
17          Emma Stone   8.0
18        Ryan Gosling   7.8
19       Anne Hathaway   7.5
20      Christian Bale   9.0
21        Kate Winslet   7.9
22        Hugh Jackman   7.5
23         Viola Davis   7.2
24     Joaquin Phoenix   8.4
25         Emily Blunt   7.5
26   Samuel L. Jackson   8.9
27           Amy Adams   7.9
28           Tom Hanks   7.8
29      Cate Blanchett   7.3

In [124]:
df2.loc[0,'Actor']= "shivani"

AttributeError: 'function' object has no attribute 'loc'

In [125]:
df2

<bound method NDFrame.copy of                  Actor  IMDb
0    Leonardo DiCaprio   8.8
1         Meryl Streep   6.9
2    Robert Downey Jr.   7.9
3   Scarlett Johansson   6.4
4            Brad Pitt   8.8
5       Angelina Jolie   6.9
6           Tom Cruise   8.3
7      Natalie Portman   8.0
8           Will Smith   7.3
9        Julia Roberts   7.1
10      Morgan Freeman   9.3
11   Jennifer Lawrence   7.2
12   Denzel Washington   7.7
13     Charlize Theron   8.1
14         Johnny Depp   8.1
15      Sandra Bullock   7.7
16          Matt Damon   8.0
17          Emma Stone   8.0
18        Ryan Gosling   7.8
19       Anne Hathaway   7.5
20      Christian Bale   9.0
21        Kate Winslet   7.9
22        Hugh Jackman   7.5
23         Viola Davis   7.2
24     Joaquin Phoenix   8.4
25         Emily Blunt   7.5
26   Samuel L. Jackson   8.9
27           Amy Adams   7.9
28           Tom Hanks   7.8
29      Cate Blanchett   7.3>

In [121]:
df

,Actor,Film,Year,Genre,Box Office,IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
1,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
2,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
3,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
5,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3
7,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
8,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
9,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
11,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
12,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
15,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
16,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
17,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
18,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
19,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
21,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
22,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
25,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
27,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
28,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
29,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3

In [126]:
df2 = df[["Actor" ,'IMDb']].copy

In [127]:
df2

<bound method NDFrame.copy of                  Actor  IMDb
0    Leonardo DiCaprio   8.8
1         Meryl Streep   6.9
2    Robert Downey Jr.   7.9
3   Scarlett Johansson   6.4
4            Brad Pitt   8.8
5       Angelina Jolie   6.9
6           Tom Cruise   8.3
7      Natalie Portman   8.0
8           Will Smith   7.3
9        Julia Roberts   7.1
10      Morgan Freeman   9.3
11   Jennifer Lawrence   7.2
12   Denzel Washington   7.7
13     Charlize Theron   8.1
14         Johnny Depp   8.1
15      Sandra Bullock   7.7
16          Matt Damon   8.0
17          Emma Stone   8.0
18        Ryan Gosling   7.8
19       Anne Hathaway   7.5
20      Christian Bale   9.0
21        Kate Winslet   7.9
22        Hugh Jackman   7.5
23         Viola Davis   7.2
24     Joaquin Phoenix   8.4
25         Emily Blunt   7.5
26   Samuel L. Jackson   8.9
27           Amy Adams   7.9
28           Tom Hanks   7.8
29      Cate Blanchett   7.3>

In [137]:
# Data Cleaning & Preprocessing
import pandas as pd

In [206]:
df3 = pd.read_csv("email - Sheet1.csv")

In [207]:
df3

,Name,Age,City,Gender,Email,Join Date
0,James Smith,28,New York,Male,james.smith@example.com,15/01/2023
1,Maria Garcia,34,Los Angeles,Female,maria.garcia@example.net,20/11/2022
2,Robert Johnson,45,Chicago,Male,rjohnson45@testmail.org,05/03/2023
3,Linda Martinez,22,Houston,Female,linda.m@service.io,12/08/2021
4,Michael Brown,31,Phoenix,Male,mbrown_phx@provider.com,28/02/2024
...,...,...,...,...,...,...
95,Grace Alexander,37,Des Moines,Female,g_alexander_dm@ia.gov,30/03/2022
96,Bryan Russell,48,Modesto,Male,b_russell_mod@ca.gov,22/01/2021
97,Rose Griffin,31,Fayetteville,Female,r_griffin_fay@nc.gov,15/06/2023
98,Logan Diaz,23,Tacoma,Male,l_diaz_tac@wa.gov,28/03/2024
99,Diana Hayes,45,Oxnard,Female,d_hayes_oxn@ca.gov,05/04/2021

In [208]:
df3.isnull()

     Name    Age   City  Gender  Email  Join Date
0   False  False  False   False  False      False
1   False  False  False   False  False      False
2   False  False  False   False  False      False
3   False  False  False   False  False      False
4   False  False  False   False  False      False
..    ...    ...    ...     ...    ...        ...
95  False  False  False   False  False      False
96  False  False  False   False  False      False
97  False  False  False   False  False      False
98  False  False  False   False  False      False
99  False  False  False   False  False      False

[100 rows x 6 columns]

In [209]:
df3.isnull().sum()

Name         0
Age          0
City         0
Gender       0
Email        0
Join Date    0
dtype: int64

In [210]:
df3.dropna() #random missing value data missing

,Name,Age,City,Gender,Email,Join Date
0,James Smith,28,New York,Male,james.smith@example.com,15/01/2023
1,Maria Garcia,34,Los Angeles,Female,maria.garcia@example.net,20/11/2022
2,Robert Johnson,45,Chicago,Male,rjohnson45@testmail.org,05/03/2023
3,Linda Martinez,22,Houston,Female,linda.m@service.io,12/08/2021
4,Michael Brown,31,Phoenix,Male,mbrown_phx@provider.com,28/02/2024
...,...,...,...,...,...,...
95,Grace Alexander,37,Des Moines,Female,g_alexander_dm@ia.gov,30/03/2022
96,Bryan Russell,48,Modesto,Male,b_russell_mod@ca.gov,22/01/2021
97,Rose Griffin,31,Fayetteville,Female,r_griffin_fay@nc.gov,15/06/2023
98,Logan Diaz,23,Tacoma,Male,l_diaz_tac@wa.gov,28/03/2024
99,Diana Hayes,45,Oxnard,Female,d_hayes_oxn@ca.gov,05/04/2021

In [211]:
df3.dropna(axis=1) #jo jo missing h usko print ni krta h baki ki chizd krta h

,Name,Age,City,Gender,Email,Join Date
0,James Smith,28,New York,Male,james.smith@example.com,15/01/2023
1,Maria Garcia,34,Los Angeles,Female,maria.garcia@example.net,20/11/2022
2,Robert Johnson,45,Chicago,Male,rjohnson45@testmail.org,05/03/2023
3,Linda Martinez,22,Houston,Female,linda.m@service.io,12/08/2021
4,Michael Brown,31,Phoenix,Male,mbrown_phx@provider.com,28/02/2024
...,...,...,...,...,...,...
95,Grace Alexander,37,Des Moines,Female,g_alexander_dm@ia.gov,30/03/2022
96,Bryan Russell,48,Modesto,Male,b_russell_mod@ca.gov,22/01/2021
97,Rose Griffin,31,Fayetteville,Female,r_griffin_fay@nc.gov,15/06/2023
98,Logan Diaz,23,Tacoma,Male,l_diaz_tac@wa.gov,28/03/2024
99,Diana Hayes,45,Oxnard,Female,d_hayes_oxn@ca.gov,05/04/2021

In [212]:
df3.fillna(0) # fillna means ki jo value missing h uski jagah 0 put krna

,Name,Age,City,Gender,Email,Join Date
0,James Smith,28,New York,Male,james.smith@example.com,15/01/2023
1,Maria Garcia,34,Los Angeles,Female,maria.garcia@example.net,20/11/2022
2,Robert Johnson,45,Chicago,Male,rjohnson45@testmail.org,05/03/2023
3,Linda Martinez,22,Houston,Female,linda.m@service.io,12/08/2021
4,Michael Brown,31,Phoenix,Male,mbrown_phx@provider.com,28/02/2024
...,...,...,...,...,...,...
95,Grace Alexander,37,Des Moines,Female,g_alexander_dm@ia.gov,30/03/2022
96,Bryan Russell,48,Modesto,Male,b_russell_mod@ca.gov,22/01/2021
97,Rose Griffin,31,Fayetteville,Female,r_griffin_fay@nc.gov,15/06/2023
98,Logan Diaz,23,Tacoma,Male,l_diaz_tac@wa.gov,28/03/2024
99,Diana Hayes,45,Oxnard,Female,d_hayes_oxn@ca.gov,05/04/2021

In [213]:
df3["Age"].fillna(df3["Age"].mean())

0     28
1     34
2     45
3     22
4     31
      ..
95    37
96    48
97    31
98    23
99    45
Name: Age, Length: 100, dtype: int64

In [214]:
df3.fillna(method="ffill")

C:\Users\shiva\AppData\Local\Temp\ipykernel_17728\1781791582.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3.fillna(method="ffill")

,Name,Age,City,Gender,Email,Join Date
0,James Smith,28,New York,Male,james.smith@example.com,15/01/2023
1,Maria Garcia,34,Los Angeles,Female,maria.garcia@example.net,20/11/2022
2,Robert Johnson,45,Chicago,Male,rjohnson45@testmail.org,05/03/2023
3,Linda Martinez,22,Houston,Female,linda.m@service.io,12/08/2021
4,Michael Brown,31,Phoenix,Male,mbrown_phx@provider.com,28/02/2024
...,...,...,...,...,...,...
95,Grace Alexander,37,Des Moines,Female,g_alexander_dm@ia.gov,30/03/2022
96,Bryan Russell,48,Modesto,Male,b_russell_mod@ca.gov,22/01/2021
97,Rose Griffin,31,Fayetteville,Female,r_griffin_fay@nc.gov,15/06/2023
98,Logan Diaz,23,Tacoma,Male,l_diaz_tac@wa.gov,28/03/2024
99,Diana Hayes,45,Oxnard,Female,d_hayes_oxn@ca.gov,05/04/2021

In [215]:
df3.fillna(method="bfill")

C:\Users\shiva\AppData\Local\Temp\ipykernel_17728\1442164819.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df3.fillna(method="bfill")

,Name,Age,City,Gender,Email,Join Date
0,James Smith,28,New York,Male,james.smith@example.com,15/01/2023
1,Maria Garcia,34,Los Angeles,Female,maria.garcia@example.net,20/11/2022
2,Robert Johnson,45,Chicago,Male,rjohnson45@testmail.org,05/03/2023
3,Linda Martinez,22,Houston,Female,linda.m@service.io,12/08/2021
4,Michael Brown,31,Phoenix,Male,mbrown_phx@provider.com,28/02/2024
...,...,...,...,...,...,...
95,Grace Alexander,37,Des Moines,Female,g_alexander_dm@ia.gov,30/03/2022
96,Bryan Russell,48,Modesto,Male,b_russell_mod@ca.gov,22/01/2021
97,Rose Griffin,31,Fayetteville,Female,r_griffin_fay@nc.gov,15/06/2023
98,Logan Diaz,23,Tacoma,Male,l_diaz_tac@wa.gov,28/03/2024
99,Diana Hayes,45,Oxnard,Female,d_hayes_oxn@ca.gov,05/04/2021

In [216]:
df3.duplicated()

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [217]:
df3.drop_duplicates() #  sari duplicate value aa jayegi

,Name,Age,City,Gender,Email,Join Date
0,James Smith,28,New York,Male,james.smith@example.com,15/01/2023
1,Maria Garcia,34,Los Angeles,Female,maria.garcia@example.net,20/11/2022
2,Robert Johnson,45,Chicago,Male,rjohnson45@testmail.org,05/03/2023
3,Linda Martinez,22,Houston,Female,linda.m@service.io,12/08/2021
4,Michael Brown,31,Phoenix,Male,mbrown_phx@provider.com,28/02/2024
...,...,...,...,...,...,...
95,Grace Alexander,37,Des Moines,Female,g_alexander_dm@ia.gov,30/03/2022
96,Bryan Russell,48,Modesto,Male,b_russell_mod@ca.gov,22/01/2021
97,Rose Griffin,31,Fayetteville,Female,r_griffin_fay@nc.gov,15/06/2023
98,Logan Diaz,23,Tacoma,Male,l_diaz_tac@wa.gov,28/03/2024
99,Diana Hayes,45,Oxnard,Female,d_hayes_oxn@ca.gov,05/04/2021

In [218]:
df3.duplicated(subset=["Name","Age"]) # kaha kaha name or age duplicate

0     False
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Length: 100, dtype: bool

In [219]:
df3["Name"].str.lower()

0         james smith
1        maria garcia
2      robert johnson
3      linda martinez
4       michael brown
           ...
95    grace alexander
96      bryan russell
97       rose griffin
98         logan diaz
99        diana hayes
Name: Name, Length: 100, dtype: object

In [220]:
df3["City"].str.contains("new york", case= False)

0      True
1     False
2     False
3     False
4     False
      ...
95    False
96    False
97    False
98    False
99    False
Name: City, Length: 100, dtype: bool

In [221]:
type(df3["City"].str.contains("new york", case= False))

pandas.core.series.Series

In [222]:
df3["Email"].str.split("@")

0      [james.smith, example.com]
1     [maria.garcia, example.net]
2      [rjohnson45, testmail.org]
3           [linda.m, service.io]
4      [mbrown_phx, provider.com]
                 ...
95       [g_alexander_dm, ia.gov]
96        [b_russell_mod, ca.gov]
97        [r_griffin_fay, nc.gov]
98           [l_diaz_tac, wa.gov]
99          [d_hayes_oxn, ca.gov]
Name: Email, Length: 100, dtype: object

In [223]:
df3["Email"].str.split("@")[0]

['james.smith', 'example.com']

In [224]:
type(df3["Email"].str.split("@")[0])

list

In [225]:
df3["Age"]=df3["Age"].astype(int)

In [226]:
df3

,Name,Age,City,Gender,Email,Join Date
0,James Smith,28,New York,Male,james.smith@example.com,15/01/2023
1,Maria Garcia,34,Los Angeles,Female,maria.garcia@example.net,20/11/2022
2,Robert Johnson,45,Chicago,Male,rjohnson45@testmail.org,05/03/2023
3,Linda Martinez,22,Houston,Female,linda.m@service.io,12/08/2021
4,Michael Brown,31,Phoenix,Male,mbrown_phx@provider.com,28/02/2024
...,...,...,...,...,...,...
95,Grace Alexander,37,Des Moines,Female,g_alexander_dm@ia.gov,30/03/2022
96,Bryan Russell,48,Modesto,Male,b_russell_mod@ca.gov,22/01/2021
97,Rose Griffin,31,Fayetteville,Female,r_griffin_fay@nc.gov,15/06/2023
98,Logan Diaz,23,Tacoma,Male,l_diaz_tac@wa.gov,28/03/2024
99,Diana Hayes,45,Oxnard,Female,d_hayes_oxn@ca.gov,05/04/2021

In [227]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       100 non-null    object
 1   Age        100 non-null    int64
 2   City       100 non-null    object
 3   Gender     100 non-null    object
 4   Email      100 non-null    object
 5   Join Date  100 non-null    object
dtypes: int64(1), object(5)
memory usage: 4.8+ KB

In [228]:
# df3["Date"]=pd.to_datetime(df3["Date"])

In [229]:
# df["Category"] = df["Category"].astype("Category")

In [230]:
df4["Age Group"]= df3["Age"].apply(lambda x :"Adult" if x >18 else "Minor")

NameError: name 'df4' is not defined

In [231]:
df4

NameError: name 'df4' is not defined

In [232]:
def isminor(x):
    return "Adult" if x >= 25 else "Minor"
df4["Age Group"]= df3["Age"].apply(lambda x :"Adult" if x >18 else "Minor")

NameError: name 'df4' is not defined

In [235]:
# gender_map = {"M": "Male", "F": "Female"}
# df3["Gender"] = df3["Gender"].map(gender_map)

###

In [238]:
# baki h vo krna h

In [239]:
df = pd.read_csv("actor - Sheet1.csv")

In [240]:
df

,Actor,Film,Year,Genre,Box Office,IMDb
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
1,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
2,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
3,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
5,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3
7,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
8,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
9,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
11,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
12,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
15,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
16,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
17,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
18,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
19,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
21,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
22,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
25,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
27,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
28,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
29,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3

df.sort_values("Year")

In [241]:
df.sort_values("Year")

,Actor,Film,Year,Genre,Box Office,IMDb
9,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
8,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
21,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
28,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
12,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
1,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
2,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
7,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
18,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
11,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
19,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
15,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
29,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3
3,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
5,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
16,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
17,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
27,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
22,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
25,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3

In [242]:
df.sort_values("Year", ascending =False)

,Actor,Film,Year,Genre,Box Office,IMDb
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
25,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
22,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
17,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
27,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
16,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
5,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
3,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
15,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
29,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3
11,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
19,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
18,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
7,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
2,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
1,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
12,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
28,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
8,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
21,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
9,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1

In [244]:
df2 =df.sort_values(["Year","IMDb"]).copy()

In [245]:
df2

,Actor,Film,Year,Genre,Box Office,IMDb
9,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
8,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
21,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
28,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
12,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
1,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
2,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
7,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
18,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
11,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
19,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
29,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3
15,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
3,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
5,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
16,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
27,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
17,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
22,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
25,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3

In [246]:
df2.reset_index()

,index,Actor,Film,Year,Genre,Box Office,IMDb
0,9,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
1,26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
2,10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
3,8,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
4,21,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
5,4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
6,28,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
7,12,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
8,14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
9,1,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
10,2,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
11,20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
12,7,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
13,0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
14,18,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
15,11,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
16,19,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
17,29,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3
18,15,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
19,3,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
20,5,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
21,16,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
22,13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
23,23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
24,27,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
25,17,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
26,22,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
27,25,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
28,24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
29,6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3

In [247]:
df2.reset_index(drop=True)

,Actor,Film,Year,Genre,Box Office,IMDb
0,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
1,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
2,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
3,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
4,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
5,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
6,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
7,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
8,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
9,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
10,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
11,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
12,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
13,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
14,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
15,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
16,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
17,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3
18,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
19,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
20,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
21,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
22,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
24,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
25,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
26,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
27,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
28,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
29,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3

In [248]:
df2

,Actor,Film,Year,Genre,Box Office,IMDb
9,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
26,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
10,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
8,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
21,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
4,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
28,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
12,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
14,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
1,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
2,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
20,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
7,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
0,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
18,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
11,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
19,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
29,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3
15,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
3,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
5,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
16,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
13,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
27,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
17,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
22,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
25,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
24,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
6,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3

In [249]:
df2.reset_index(drop=True, inplace=True)

In [250]:
df2

,Actor,Film,Year,Genre,Box Office,IMDb
0,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1
1,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9
2,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3
3,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3
4,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9
5,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8
6,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8
7,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7
8,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1
9,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9
10,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9
11,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0
12,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0
13,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8
14,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8
15,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2
16,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5
17,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3
18,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7
19,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4
20,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9
21,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0
22,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2
24,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9
25,Emma Stone,La La Land,2016,Musical,$448.9M,8.0
26,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5
27,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5
28,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4
29,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3

In [ ]:
df.sort_index

In [255]:
df2["Rank"]= df2["IMDb"].rank(ascending=False)

##

In [256]:
df2

,Actor,Film,Year,Genre,Box Office,IMDb,Rank
0,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1,27.0
1,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9,3.0
2,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3,1.0
3,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3,23.5
4,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9,14.0
5,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8,4.5
6,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8,16.5
7,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7,18.5
8,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1,8.5
9,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9,28.5
10,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9,14.0
11,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0,2.0
12,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0,11.0
13,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8,4.5
14,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8,16.5
15,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2,25.5
16,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5,21.0
17,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3,23.5
18,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7,18.5
19,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4,30.0
20,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9,28.5
21,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0,11.0
22,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1,8.5
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2,25.5
24,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9,14.0
25,Emma Stone,La La Land,2016,Musical,$448.9M,8.0,11.0
26,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5,21.0
27,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5,21.0
28,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4,6.0
29,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3,7.0

In [259]:
df2["Rank"]= df2["IMDb"].rank(ascending=True , method = "dense")

In [260]:
df2

,Actor,Film,Year,Genre,Box Office,IMDb,Rank
0,Julia Roberts,Pretty Woman,1990,Romance,$463.4M,7.1,3.0
1,Samuel L. Jackson,Pulp Fiction,1994,Crime,$213.9M,8.9,15.0
2,Morgan Freeman,The Shawshank Redemption,1994,Drama,$28.8M,9.3,17.0
3,Will Smith,Men in Black,1997,Sci-Fi,$589.4M,7.3,5.0
4,Kate Winslet,Titanic,1997,Romance,$2.257B,7.9,9.0
5,Brad Pitt,Fight Club,1999,Drama,$101.2M,8.8,14.0
6,Tom Hanks,Cast Away,2000,Adventure,$429.6M,7.8,8.0
7,Denzel Washington,Training Day,2001,Crime,$104.9M,7.7,7.0
8,Johnny Depp,Pirates of the Caribbean,2003,Adventure,$654.3M,8.1,11.0
9,Meryl Streep,The Devil Wears Prada,2006,Comedy/Drama,$326.7M,6.9,2.0
10,Robert Downey Jr.,Iron Man,2008,Action,$585.8M,7.9,9.0
11,Christian Bale,The Dark Knight,2008,Action,$1.006B,9.0,16.0
12,Natalie Portman,Black Swan,2010,Thriller,$329.4M,8.0,10.0
13,Leonardo DiCaprio,Inception,2010,Sci-Fi,$836.8M,8.8,14.0
14,Ryan Gosling,Drive,2011,Crime,$81.4M,7.8,8.0
15,Jennifer Lawrence,The Hunger Games,2012,Sci-Fi,$694.4M,7.2,4.0
16,Anne Hathaway,Les Misérables,2012,Musical,$441.8M,7.5,6.0
17,Cate Blanchett,Blue Jasmine,2013,Drama,$97.5M,7.3,5.0
18,Sandra Bullock,Gravity,2013,Sci-Fi,$723.2M,7.7,7.0
19,Scarlett Johansson,Lucy,2014,Action/Sci-Fi,$463.4M,6.4,1.0
20,Angelina Jolie,Maleficent,2014,Fantasy,$758.5M,6.9,2.0
21,Matt Damon,The Martian,2015,Sci-Fi,$630.2M,8.0,10.0
22,Charlize Theron,Mad Max: Fury Road,2015,Action,$380.4M,8.1,11.0
23,Viola Davis,Fences,2016,Drama,$64.4M,7.2,4.0
24,Amy Adams,Arrival,2016,Sci-Fi,$203.4M,7.9,9.0
25,Emma Stone,La La Land,2016,Musical,$448.9M,8.0,10.0
26,Hugh Jackman,The Greatest Showman,2017,Musical,$435.0M,7.5,6.0
27,Emily Blunt,A Quiet Place,2018,Horror,$341.0M,7.5,6.0
28,Joaquin Phoenix,Joker,2019,Crime,$1.074B,8.4,13.0
29,Tom Cruise,Top Gun: Maverick,2022,Action,$1.496B,8.3,12.0

In [263]:
df = df[["Film", "Actor", "Year", "Genre", "IMDb", "Box Office"]]

In [264]:
df

,Film,Actor,Year,Genre,IMDb,Box Office
0,Inception,Leonardo DiCaprio,2010,Sci-Fi,8.8,$836.8M
1,The Devil Wears Prada,Meryl Streep,2006,Comedy/Drama,6.9,$326.7M
2,Iron Man,Robert Downey Jr.,2008,Action,7.9,$585.8M
3,Lucy,Scarlett Johansson,2014,Action/Sci-Fi,6.4,$463.4M
4,Fight Club,Brad Pitt,1999,Drama,8.8,$101.2M
5,Maleficent,Angelina Jolie,2014,Fantasy,6.9,$758.5M
6,Top Gun: Maverick,Tom Cruise,2022,Action,8.3,$1.496B
7,Black Swan,Natalie Portman,2010,Thriller,8.0,$329.4M
8,Men in Black,Will Smith,1997,Sci-Fi,7.3,$589.4M
9,Pretty Woman,Julia Roberts,1990,Romance,7.1,$463.4M
10,The Shawshank Redemption,Morgan Freeman,1994,Drama,9.3,$28.8M
11,The Hunger Games,Jennifer Lawrence,2012,Sci-Fi,7.2,$694.4M
12,Training Day,Denzel Washington,2001,Crime,7.7,$104.9M
13,Mad Max: Fury Road,Charlize Theron,2015,Action,8.1,$380.4M
14,Pirates of the Caribbean,Johnny Depp,2003,Adventure,8.1,$654.3M
15,Gravity,Sandra Bullock,2013,Sci-Fi,7.7,$723.2M
16,The Martian,Matt Damon,2015,Sci-Fi,8.0,$630.2M
17,La La Land,Emma Stone,2016,Musical,8.0,$448.9M
18,Drive,Ryan Gosling,2011,Crime,7.8,$81.4M
19,Les Misérables,Anne Hathaway,2012,Musical,7.5,$441.8M
20,The Dark Knight,Christian Bale,2008,Action,9.0,$1.006B
21,Titanic,Kate Winslet,1997,Romance,7.9,$2.257B
22,The Greatest Showman,Hugh Jackman,2017,Musical,7.5,$435.0M
23,Fences,Viola Davis,2016,Drama,7.2,$64.4M
24,Joker,Joaquin Phoenix,2019,Crime,8.4,$1.074B
25,A Quiet Place,Emily Blunt,2018,Horror,7.5,$341.0M
26,Pulp Fiction,Samuel L. Jackson,1994,Crime,8.9,$213.9M
27,Arrival,Amy Adams,2016,Sci-Fi,7.9,$203.4M
28,Cast Away,Tom Hanks,2000,Adventure,7.8,$429.6M
29,Blue Jasmine,Cate Blanchett,2013,Drama,7.3,$97.5M

In [1]:
import pandas as pd

# Sample DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Math': [85, 78, 92],
    'Science': [90, 82, 89],
    'English': [88, 85, 94]
}

df = pd.DataFrame(data)

# Display the DataFrame
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  Charlie    92       89       94

In [ ]:
#using melt

In [2]:
df.melt(id_vars=["Name"], value_vars=["Math","Science","English"], var_name="Subject",value_name="Score")

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  Charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  Charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  Charlie  English     94

In [3]:
# using pivot

In [4]:
df.pivot(index="Name",columns="Subject",values="Score")

KeyError: 'Subject'

In [5]:
# if there is duplicate name or numbers in marks then we used pivot table

In [6]:
df.pivot_table(index="Name",columns="Subject",values="Score", aggfunc="mean")

KeyError: 'Score'

In [7]:
# Aggregration & Grouping

In [8]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [9]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [10]:
df.groupby("Department")["Salary"].mean() #average salary dikhne ke liye

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [11]:
type(df.groupby("Department")["Salary"].mean())

pandas.core.series.Series

In [12]:
df.groupby("Team")["Salary"].sum()

Team
A    175
B    163
C    180
D    155
Name: Salary, dtype: int64

In [13]:
df.groupby("Team")["Salary"].max()

Team
A    90
B    85
C    92
D    80
Name: Salary, dtype: int64

In [14]:
df.groupby("Team")["Salary"].min()

Team
A    85
B    78
C    88
D    75
Name: Salary, dtype: int64

In [15]:
df.groupby("Team")["Salary"].count()

Team
A    2
B    2
C    2
D    2
Name: Salary, dtype: int64

In [16]:
# .agg and aggregate

In [18]:
df.groupby("Team")["Salary"].agg(["mean", "max", "min","count"])

      mean  max  min  count
Team
A     87.5   90   85      2
B     81.5   85   78      2
C     90.0   92   88      2
D     77.5   80   75      2

In [19]:
df.groupby("Team")["Salary"].agg(
    avg_score="mean",
    high_score="max"
)

      avg_score  high_score
Team
A          87.5          90
B          81.5          85
C          90.0          92
D          77.5          80

In [20]:
df["Team Avg"] = df.groupby("Team")["Salary"].transform("mean")

In [21]:
df

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [24]:
df.groupby("Team").filter(lambda x: x["Salary"].mean() > 85)

  Department Team Gender  Salary  Age   JoinDate  Team Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0

In [25]:
# Merging & Joining Data

In [26]:
employees = pd.DataFrame({"EmpID": [1,2,3], "Name" :["Alice","Bob","shiv"], "DeptID": [10,20,30]})

In [27]:
employees

   EmpID   Name  DeptID
0      1  Alice      10
1      2    Bob      20
2      3   shiv      30

In [30]:
departments = pd.DataFrame({ "DeptID": [10,20,40], "DeptName":["HR","Engineering","Marketing"]})

In [31]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [32]:
pd.merge(employees,departments, on = "DeptID") #inner join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [33]:
pd.merge(employees,departments, on = "DeptID", how ="left") #left join

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering
2      3   shiv      30          NaN

In [34]:
pd.merge(employees,departments, on = "DeptID", how ="right") #right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [35]:
pd.merge(employees,departments, on = "DeptID", how ="outer") #outer join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    3.0   shiv      30          NaN
3    NaN    NaN      40    Marketing

In [44]:
df1 = pd.DataFrame({"Name":["Alice","Bob"] , "Score": [433,444]})
df2 = pd.DataFrame({"Name":["shiv","kalu"], "Age": [23,44]})

In [45]:
df1

    Name  Score
0  Alice    433
1    Bob    444

In [46]:
df2

   Name  Age
0  shiv   23
1  kalu   44

In [47]:
# concatenate

In [48]:
pd.concat([df1,df2])

    Name  Score   Age
0  Alice  433.0   NaN
1    Bob  444.0   NaN
0   shiv    NaN  23.0
1   kalu    NaN  44.0

In [49]:
pd.concat([df1,df2], axis = 1)

    Name  Score  Name  Age
0  Alice    433  shiv   23
1    Bob    444  kalu   44

In [51]:
pd.concat([df1,df2], axis = 0)

    Name  Score   Age
0  Alice  433.0   NaN
1    Bob  444.0   NaN
0   shiv    NaN  23.0
1   kalu    NaN  44.0